### ISSUE TITLE
Dataset Folder Structure

### ISSUE THREAD

**Issue by prter12** [alexhe101/Pan-Mamba#12]
I noticed that in the option.yml file of the code, the dataset path only goes up to the folder level. I'd like to ask how the specific folders ms, pan, and gt are arranged within the dataset folder.

**Comment by alexhe101** [comment]
Here is the example:
WV2/train128/ms/1.tif,2.tif....
WV2/train128/pan/1.tif,2.tif...
MS folder contains the GT image.
 LRMS is generated in the training process, you can refer to dataset.py
