### ISSUE TITLE
关于z激活，在代码里面的体现在？

### ISSUE THREAD

**Issue by zzduoYI** [alexhe101/Pan-Mamba#13]
![a9d54e3318d5f7e3d02dc1bee57ecbe](https://github.com/alexhe101/Pan-Mamba/assets/53027174/5f8d42e7-51ee-4a9c-b33e-fa3fc047340f)
这个我没看到在代码中的体现呀，能否告知一下？
在此表示感谢

**Comment by alexhe101** [comment]
这是mamba原始论文里的实现，我们直接调用了该函数，可以参考https://github.com/hustvl/Vim/blob/main/mamba-1p1p1/mamba_ssm/ops/selective_scan_interface.py#L606
