### ISSUE TITLE
能否发布下mamba_ssm

### ISSUE THREAD

**Issue by nbhuangzhixuan** [alexhe101/Pan-Mamba#14]
我现在使用的是vim的mamba_ssm,跟作者您的代码不一致，导致有报错
    self.cross_mamba = Mamba(dim,bimamba_type="v3")
TypeError: __init__() got an unexpected keyword argument 'bimamba_type'
如果可以的话能否发布下您的mamba_ssm，发送到我的邮箱也可以854725844@qq.com，万分感谢！

**Comment by nbhuangzhixuan** [comment]
这是修改mamba_simple.py后的报错
    global_f = self.cross_mamba(self.norm1(ms),extra_emb=self.norm2(pan))
  File "/data2/lsl/anaconda3/envs/hzx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/lsl/anaconda3/envs/hzx/lib/python3.9/site-packages/mamba_ssm/modules/mamba_simple.py", line 264, in forward
    out = mamba_inner_fn_no_out_proj(
  File "/data2/lsl/anaconda3/envs/hzx/lib/python3.9/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 632, in mamba_inner_fn_no_out_proj
    return MambaInnerFnNoOutProj.apply(xz, conv1d_weight, conv1d_bias, x_proj_weight, delta_proj_weight,
  File "/data2/lsl/anaconda3/envs/hzx/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/data2/lsl/anaconda3/envs/hzx/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 98, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/data2/lsl/anaconda3/envs/hzx/lib/python3.9/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 177, in forward
    conv1d_out = causal_conv1d_cuda.causal_conv1d_fwd(x, conv1d_weight, conv1d_bias,None, True)
TypeError: causal_conv1d_fwd(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: Optional[torch.Tensor], arg3: Optional[torch.Tensor], arg4: Optional[torch.Tensor], arg5: Optional[torch.Tensor], arg6: bool) -> torch.Tensor

Invoked with: tensor([[[ 0.1246, -0.0831, -0.0404,  ...,  0.4614,  0.4897,  0.5169],
         [ 0.2003,  0.3418,  0.3105,  ...,  0.1574,  0.0612,  0.0855],
         [ 1.0184,  0.7201,  0.7180,  ...,  0.6715,  0.6886,  0.8125],
         ...,
         [ 0.0289, -0.0569, -0.0780,  ..., -0.2822, -0.2473, -0.2172],
         [-0.5571, -0.4720, -0.4450,  ..., -0.5825, -0.6726, -0.7100],
         [ 0.0904,  0.2147,  0.1697,  ..., -0.2380, -0.2820, -0.0138]],

        [[ 0.1253, -0.0446, -0.0726,  ...,  0.4369,  0.4299,  0.5519],
         [ 0.2245,  0.2922,  0.3302,  ...,  0.1218,  0.1495,  0.1143],
         [ 1.0255,  0.7282,  0.7096,  ...,  0.7339,  0.6760,  0.8245],
         ...,
         [ 0.0613, -0.0949, -0.0754,  ..., -0.2713, -0.3162, -0.2284],
         [-0.5438, -0.4697, -0.4592,  ..., -0.6195, -0.5906, -0.6301],
         [ 0.0632,  0.2210,  0.2265,  ..., -0.3159, -0.2451, -0.0364]]],
       device='cuda:0', requires_grad=True), tensor([[ 0.3851, -0.3866,  0.1973,  0.4624],
        [-0.1734, -0.0373,  0.1995, -0.3953],
        [ 0.2151, -0.4804,  0.4445,  0.1828],
        ...,
        [ 0.3604, -0.1935, -0.3096,  0.1059],
        [-0.2766, -0.4932, -0.2952, -0.3474],
        [-0.2469,  0.2993,  0.0825, -0.4144]], device='cuda:0',
       requires_grad=True), Parameter containing:
tensor([ 0.0161,  0.0664, -0.2070,  ...,  0.2443, -0.0121, -0.3372],

**Comment by chenzean** [comment]
这个问题解决了吗

**Comment by nbhuangzhixuan** [comment]
还没有，作者您用的是vim的selective_scan_interface.py吗，我应该是这里面的causal_conv1d_cuda.causal_conv1d_fwd和causal_conv1d_cuda.causal_conv1d_bwd传入的参数个数不一致导致的这个报错

**Comment by nbhuangzhixuan** [comment]
已解决，是我的casual_conv1d版本是1.2.0太高了,修改了一下causal_conv1d_cuda.causal_conv1d_fwd和causal_conv1d_cuda.causal_conv1d_bwd参数解决了，感谢！

**Comment by alexhe101** [comment]
感谢您的关注，我会加上requirements.txt
