### ISSUE TITLE
关于data/dataset.py的问题

### ISSUE THREAD

**Issue by sunzhiyu233** [alexhe101/Pan-Mamba#15]
在data/dataset.py的第197行中
lms_image = ms_image.crop((0, 0, lms_image.size[0] // self.upscale_factor * self.upscale_factor, lms_image.size[1] // self.upscale_factor * self.upscale_factor))
ms_image并没有被定义

**Comment by alexhe101** [comment]
Data_eval class在本代码中没有被用到,应该没有影响

**Comment by xiaowangtongxue-1** [comment]
您好，请问数据集公开嘛
