### ISSUE TITLE
self.cross_mamba = Mamba(dim,bimamba_type="v3")

### ISSUE THREAD

**Issue by fgwwd00000** [alexhe101/Pan-Mamba#16]
我在这一行遇见了错误，self.cross_mamba = Mamba(dim,bimamba_type="v3")，显示mamba.forward() got an unexpected keyword argument 'extra_emb',源文件里面替换过了仍然没有找到v3

**Comment by alexhe101** [comment]
是不是您没有替换成功:
参考代码:
https://github.com/alexhe101/Pan-Mamba/blob/main/Mamba-block/mamba_simple.py#L170C1-L171C1
函数中是有extra_emb的
