### ISSUE TITLE
张量维度

### ISSUE THREAD

**Issue by Z-Z188** [alexhe101/Pan-Mamba#21]
作者您好，感谢您的工作！
![image](https://github.com/user-attachments/assets/8a1f9725-e283-4b6b-acb8-edb3fc01a875)
由于没有提供数据集，所以我想请问作者输入deep feature fusion的张量维度是什么呢
期待作者的回答，谢谢！

**Comment by alexhe101** [comment]
输入的ms大小是（B,C,H,W)=(4,4,32,32)
PAN是(4,1,128,128)
