### ISSUE TITLE
Request for Permission to Use test Images with Pan-Mamba Model

### ISSUE THREAD

**Issue by XCZhou520** [alexhe101/Pan-Mamba#3]
Dear Pan-Mamba Team,

I hope this message finds you well. I recently came across your impressive work on the Pan-Mamba model, designed for pan-sharpening satellite images, and I am very interested in exploring its capabilities.

I understand that the Pan-Mamba model has been trained on the WV2, WV3, and Gaofen-2 satellites, specifically focusing on 4-channel images (RGB and Near-Infrared). I also note that the training datasets you used are not publicly available. I respect the confidentiality and restrictions around your training datasets.

In line with this, I would like to request your permission to upload a few of my own satellite images to test the Pan-Mamba model. I understand the importance of respecting intellectual property and would adhere to any guidelines or conditions you may set forth for using the Pan-Mamba model. If possible, I would also appreciate any suggestions or advice you might have about using the model most effectively.

Thank you for considering my request. I look forward to potentially using the Pan-Mamba model and contributing to its application in new areas.

Best regards,

xczhou

**Comment by alexhe101** [comment]
Our Git repository already includes pre-trained weights, and you can use the Mamba model to test your images. Wishing you success in using our model!
