### ISSUE TITLE
I use your mamba-block/mamba_simple.py  to replace orginal installed mamba_simple.py.  How can i solve this problem. Thank you.

### ISSUE THREAD

**Issue by Jamie-Cheung** [alexhe101/Pan-Mamba#7]
![image](https://github.com/alexhe101/Pan-Mamba/assets/100945715/5b94eb6f-fce8-4f3a-85db-c73cd5bbee67)
/

**Comment by alexhe101** [comment]
It seems line 19 has not worked well; it may be that mamba_ssm was installed unsuccessfully.

**Comment by Jamie-Cheung** [comment]
> It seems line 19 has not worked well; it may be that mamba_ssm was installed unsuccessfully.

In fact, I have executed "pip install mamba-ssm" successfully.  
For example: Requirement already satisfied: mamba-ssm in /home/zzj/anaconda3/envs/mamba/lib/python3.8/site-packages (1.0.1)
In addition, I noticed that you imported bimamba_inner_fn, mamba_inner_fn_no_out_proj from mamba_ssm.ops.selective_scan_interface, which is absent from the original mamba_simple-.py.

**Comment by alexhe101** [comment]
If that is so, you can try to delete lines 18–21.
The imported function/classes is written in [vmamba](https://github.com/hustvl/Vim/blob/main/mamba-1p1p1/mamba_ssm/modules/mamba_simple.py), not in the original mamba package.

**Comment by alexhe101** [comment]
Have you tried these commands?
pip install -e causal_conv1d>=1.1.0
pip install -e mamba-1p1p1

**Comment by Jamie-Cheung** [comment]
> Have you tried these commands? pip install -e causal_conv1d>=1.1.0 pip install -e mamba-1p1p1

pip install -e causal_conv1d>=1.1.0 -i https://mirrors.aliyun.com/pypi/simple/
ERROR: causal_conv1d is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

It seems that I fail to install these packages. I found that the project in vmamba contains these two files, can I copy them and use them.

**Comment by alexhe101** [comment]
Yes, you should follow their instructions to install vmamba first, then replace their mamba_simple.py with my version.

**Comment by stanny880913** [comment]
> > Have you tried these commands? pip install -e causal_conv1d>=1.1.0 pip install -e mamba-1p1p1
> 
> pip install -e causal_conv1d>=1.1.0 -i https://mirrors.aliyun.com/pypi/simple/ ERROR: causal_conv1d is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
> 
> It seems that I fail to install these packages. I found that the project in vmamba contains these two files, can I copy them and use them.

Hello, Did you solved the problem? what can I do to sole it? thx

**Comment by Jamie-Cheung** [comment]
> > > Have you tried these commands? pip install -e causal_conv1d>=1.1.0 pip install -e mamba-1p1p1
> > 
> > 
> > pip install -e causal_conv1d>=1.1.0 -i https://mirrors.aliyun.com/pypi/simple/ ERROR: causal_conv1d is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
> > It seems that I fail to install these packages. I found that the project in vmamba contains these two files, can I copy them and use them.
> 
> Hello, Did you solved the problem? what can I do to sole it? thx

I have solve the promblem by following this: https://zhuanlan.zhihu.com/p/687359086

**Comment by stanny880913** [comment]
> > > > Have you tried these commands? pip install -e causal_conv1d>=1.1.0 pip install -e mamba-1p1p1
> > > 
> > > 
> > > pip install -e causal_conv1d>=1.1.0 -i https://mirrors.aliyun.com/pypi/simple/ ERROR: causal_conv1d is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
> > > It seems that I fail to install these packages. I found that the project in vmamba contains these two files, can I copy them and use them.
> > 
> > 
> > Hello, Did you solved the problem? what can I do to sole it? thx
> 
> I have solve the promblem by following this: https://zhuanlan.zhihu.com/p/687359086

What is your torch and cuda version, mine are torch=1.13.1 and cuda 11.7, can this success?

**Comment by stanny880913** [comment]
> > > > Have you tried these commands? pip install -e causal_conv1d>=1.1.0 pip install -e mamba-1p1p1
> > > 
> > > 
> > > pip install -e causal_conv1d>=1.1.0 -i https://mirrors.aliyun.com/pypi/simple/ ERROR: causal_conv1d is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
> > > It seems that I fail to install these packages. I found that the project in vmamba contains these two files, can I copy them and use them.
> > 
> > 
> > Hello, Did you solved the problem? what can I do to sole it? thx
> 
> I have solve the promblem by following this: https://zhuanlan.zhihu.com/p/687359086

Did you do this step?
```
不必惊慌！首先找到你所创建的环境里的mamba_ssm文件夹，路径一般在这里："/envs/mamba/lib/python3.10/site-packages/mamba_ssm/"，将其替换为你项目代码里的mamba_ssm文件夹：

rm -rf "/envs/mamba/lib/python3.10/site-packages/mamba_ssm/" (删除原环境里的mamba_ssm)

cp -r "Vim-main/mamba-1p1p1/mamba_ssm" "/envs/mamba/lib/python3.10/site-packages/" (将项目code里的mamba_ssm文件夹替换进去)



此时，轻舟已过万重山，终于安装好了Vim的环境！！！接下来你可以运行你的代码啦......
```

**Comment by Jamie-Cheung** [comment]
> > > > > Have you tried these commands? pip install -e causal_conv1d>=1.1.0 pip install -e mamba-1p1p1
> > > > 
> > > > 
> > > > pip install -e causal_conv1d>=1.1.0 -i https://mirrors.aliyun.com/pypi/simple/ ERROR: causal_conv1d is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
> > > > It seems that I fail to install these packages. I found that the project in vmamba contains these two files, can I copy them and use them.
> > > 
> > > 
> > > Hello, Did you solved the problem? what can I do to sole it? thx
> > 
> > 
> > I have solve the promblem by following this: https://zhuanlan.zhihu.com/p/687359086
> 
> Did you do this step?
> 
> ```
> 不必惊慌！首先找到你所创建的环境里的mamba_ssm文件夹，路径一般在这里："/envs/mamba/lib/python3.10/site-packages/mamba_ssm/"，将其替换为你项目代码里的mamba_ssm文件夹：
> 
> rm -rf "/envs/mamba/lib/python3.10/site-packages/mamba_ssm/" (删除原环境里的mamba_ssm)
> 
> cp -r "Vim-main/mamba-1p1p1/mamba_ssm" "/envs/mamba/lib/python3.10/site-packages/" (将项目code里的mamba_ssm文件夹替换进去)
> 
> 
> 
> 此时，轻舟已过万重山，终于安装好了Vim的环境！！！接下来你可以运行你的代码啦......
> ```

Yes

**Comment by stanny880913** [comment]
> > > > > > Have you tried these commands? pip install -e causal_conv1d>=1.1.0 pip install -e mamba-1p1p1
> > > > > 
> > > > > 
> > > > > pip install -e causal_conv1d>=1.1.0 -i https://mirrors.aliyun.com/pypi/simple/ ERROR: causal_conv1d is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
> > > > > It seems that I fail to install these packages. I found that the project in vmamba contains these two files, can I copy them and use them.
> > > > 
> > > > 
> > > > Hello, Did you solved the problem? what can I do to sole it? thx
> > > 
> > > 
> > > I have solve the promblem by following this: https://zhuanlan.zhihu.com/p/687359086
> > 
> > 
> > Did you do this step?
> > ```
> > 不必惊慌！首先找到你所创建的环境里的mamba_ssm文件夹，路径一般在这里："/envs/mamba/lib/python3.10/site-packages/mamba_ssm/"，将其替换为你项目代码里的mamba_ssm文件夹：
> > 
> > rm -rf "/envs/mamba/lib/python3.10/site-packages/mamba_ssm/" (删除原环境里的mamba_ssm)
> > 
> > cp -r "Vim-main/mamba-1p1p1/mamba_ssm" "/envs/mamba/lib/python3.10/site-packages/" (将项目code里的mamba_ssm文件夹替换进去)
> > 
> > 
> > 
> > 此时，轻舟已过万重山，终于安装好了Vim的环境！！！接下来你可以运行你的代码啦......
> > ```
> 
> Yes

when finished this step, then replace their mamba_simple.py with pan mamba version?

**Comment by Jamie-Cheung** [comment]
> > > > > > > Have you tried these commands? pip install -e causal_conv1d>=1.1.0 pip install -e mamba-1p1p1
> > > > > > 
> > > > > > 
> > > > > > pip install -e causal_conv1d>=1.1.0 -i https://mirrors.aliyun.com/pypi/simple/ ERROR: causal_conv1d is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
> > > > > > It seems that I fail to install these packages. I found that the project in vmamba contains these two files, can I copy them and use them.
> > > > > 
> > > > > 
> > > > > Hello, Did you solved the problem? what can I do to sole it? thx
> > > > 
> > > > 
> > > > I have solve the promblem by following this: https://zhuanlan.zhihu.com/p/687359086
> > > 
> > > 
> > > Did you do this step?
> > > ```
> > > 不必惊慌！首先找到你所创建的环境里的mamba_ssm文件夹，路径一般在这里："/envs/mamba/lib/python3.10/site-packages/mamba_ssm/"，将其替换为你项目代码里的mamba_ssm文件夹：
> > > 
> > > rm -rf "/envs/mamba/lib/python3.10/site-packages/mamba_ssm/" (删除原环境里的mamba_ssm)
> > > 
> > > cp -r "Vim-main/mamba-1p1p1/mamba_ssm" "/envs/mamba/lib/python3.10/site-packages/" (将项目code里的mamba_ssm文件夹替换进去)
> > > 
> > > 
> > > 
> > > 此时，轻舟已过万重山，终于安装好了Vim的环境！！！接下来你可以运行你的代码啦......
> > > ```
> > 
> > 
> > Yes
> 
> when finished this step, then replace their mamba_simple.py with pan mamba version?

Yes
