### ISSUE TITLE
求助：LayerNorm归一化及反归一化的问题

### ISSUE THREAD

**Issue by 1083290054** [alexhe101/Pan-Mamba#9]
您好，我在复现您的代码时发现一个问题，在您设计的Mamba块中多次使用了LayerNorm来进行归一化操作，但是好像并没有进行反归一化的操作，在模型最后的语句     hrms = self.output(ms_f)+ms_bic 中，前一项是多个Mamba块输出的结果，值的范围很小很小，后一项是模型的初始输入，这两项相加之后前一项的效果似乎完全没有作用。这也就导致模型输出结果同原始输入相差无几。我反复调试后无果，想寻求您的帮助，谢谢

**Comment by alexhe101** [comment]
1. 在每个block中使用layernorm是惯例，如transformer也是相同的操作
2. hrms = self.output(ms_f)+ms_bic是因为pan-sharpening任务本质是个超分辨率任务，也就是学习的目标是bicubic上采样和hrms之间的高频残差，所以对于大部分区域self.output(ms_f)的值都比较小，如果您的任务不同，可以移除ms_bic

**Comment by 1083290054** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
